#
# This is a full customization, replacing wands and spells with guns and
# other combat weapons.
#

# No SP here, for now
sp_enabled: false

# Use a special RP
resource_pack: war

# Use a different RP when combined with other configs
add_resource_pack: all
